version: '3'

services:
  app:
    image: ncight-data-upload-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./lib:/app/lib