version: '3'

services:
  app:
    image: ncight-data-upload-dev
    hostname: nextjsapp
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./lib:/app/lib
  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - app