import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Amplify } from 'aws-amplify'
import useEnv from '../lib/useEnv'
import { ChakraProvider, ColorModeScript } from '@chakra-ui/react'
import "@fontsource/roboto-condensed/700.css"
import {customTheme} from "../styles/theme";

function MyApp({ Component, pageProps }: AppProps) {
  const { env } = useEnv()
  if (!env) return <>No Env Loading...</>

  Amplify.configure({
    Auth: {
      userPoolId: env.cognitoUserPoolId,
      userPoolWebClientId: env.cognitoUserPoolWebClientId,
    },
  })

  return (
    <>
      <ChakraProvider theme={customTheme}>
        <Head>
          <title>Create Next App Development</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ColorModeScript initialColorMode={customTheme.config.initialColorMode} />
        <Component {...pageProps} />
      </ChakraProvider>
    </>
  )
}

export default MyApp
