import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Amplify } from 'aws-amplify'
import { ChakraProvider, ColorModeScript } from '@chakra-ui/react'
import "@fontsource/roboto-condensed/700.css"
import {customTheme} from "../styles/theme";

Amplify.configure({
  Auth: {
    userPoolId: process.env.NEXT_PUBLIC_AUTH_USER_POOL_ID,
    userPoolWebClientId: process.env.NEXT_PUBLIC_AUTH_WEB_CLIENT_ID,
    ssr: true,
  }
})

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <ChakraProvider theme={customTheme}>
        <Head>
          <title>Create Next App Development</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ColorModeScript initialColorMode={customTheme.config.initialColorMode} />
          <Component {...pageProps} />
      </ChakraProvider>
    </>
  )
}

export default MyApp
